version: '2'
volumes:
  transmission:
    name: transmission
  jdownloader:
    name: jdownloader

networks:
  internal-network:
    external: true
    name: virtual_net

services:
  #download client
  transmission:
    image: ghcr.io/linuxserver/transmission
    container_name: transmission
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    #      - TRANSMISSION_WEB_HOME=/combustion-release/ #optional
    #      - USER=username #optional
    #      - PASS=password #optional
    #      - WHITELIST=iplist #optional
    #      - HOST_WHITELIST=dnsnane list #optional
    volumes:
      - transmission:/config
      - ${USERDIR}:/downloads
      - ${USERDIR}:/watch
    ports:
      - 9091:9091
      - 51413:51413
      - 51413:51413/udp
    networks:
      - internal-network
    restart: unless-stopped